### ISSUE TITLE
IC2 Classic

### ISSUE THREAD

**Issue by Speiger** [Unity-Resource-Pack/Unity-Modded#90]
Could you add IC2 Classic Support? It can be combined with IC2 Exp in Textures (it uses the same folder but differend subfolders)

**Comment by CyanideX** [comment]
The day has come.

**Comment by CyanideX** [comment]
Why aren't there any blockstate or model folders in assets? 😕

**Comment by Speiger** [comment]
@CyanideX yep, I don't allow custom models.
You can replace textures, which are no longer sprite sheets, but we want to be special.
And after reading what mojang changes in 1.19.3 this saves me weeks of work if i decide to port to that version.
Edit:
I planned to do custom model support, but after everything ended i thought, nope not worth the time.

**Comment by Speiger** [comment]
Small side note, i wrote my texture system so that you can replace any side if you wish to do so without models.
It uses a custom loader that compresses textures to reduce the usage of the,

**Comment by CyanideX** [comment]
I tried replacing all instances of the macerator in both the ic2 and ic2dev folders but they remained unchanged in game. It isn't clear which textures are being used so I might have to return to this when the mod is further along into 1.19.

**Comment by Speiger** [comment]
the texture_package.json is the file that decides which "file" is being used.
Just copy that to and adjust the "Locations" accordingly.

The Packages are designed to filter out duplicates, but they are basically "key" to "resource location".
In other words these texture_package.json are symlink providers.

**Comment by ChloeDawn** [comment]
Do you have any benchmarks to show that these "optimizations" are worthwhile? All I see is that you've arbitrarily restricted customisation for end users and effectively disabled a vanilla API.

**Comment by Speiger** [comment]
@ChloeDawn why isn't the CPU running directly on HDD/SSD instead of ram and Caches?
If a file has to be only loaded once (even larger) vs a tone of tiny files. Believe me you safe a lot of time.
That covers 1.12.

Now the only reason we went away from that is MC actually now uses more cores which effectively makes that optimization useless since you throw resources against the wall to achieve higher performance.


About the optimizations for models.
Lets use cables for a example:
Cables have Blocks have custom models because they require them.
The have 4096 (64*64) Connectivity states. Which are on average 36 quads each.
Thanks to the custom models these are not blockstates but ModelData. And due to recycling only 72 quads per block states.
4096 blockstates are still fine with vanilla load times. Might add 4-5 seconds to the game in load time.

But these blocks can be dyed, foamed, might have redstone interactivity, and might have insulation. Which is on average 17 * 3 * (3-5) block states on average. So 51 - 153 - 255 BlockStates from lowest to average to highest.
If I were to use json models that can get up to 1 Million BlockStates/Models with 36 quads on average. (so 36 million cached baked quads)
With a custom model its 18360 quads (255 * 72)

Dunno you tell me if a custom model system that doesn't use json is worth it? For 1 block out of 12-15 blocks?
And TESR while less memory usage/cpu(loadtimes) is a lot slower since every quad on the TESR is slower rendered on CPU in 1.14+ (irrc) then it is in 1.12 or older.

Why? because minecraft runs matrix operations (where the GPU outclasses the CPU) on the CPU to achieve the same type of rendering that GL1.0 made. So TESR is also not a good solution. Because you pay on average FPS if a lot of cables are placed.
Chunk Rendering is the most efficient since the it uses 1 matrix calculation per render type instead of per block. Which is 4-6 per chunk at max.

**Comment by Speiger** [comment]
@CyanideX if you are willing to work with me, I would help you get things running and if you need something special I can look into it as needed. But if you give up the 1 second after something not working then it is fine if this never happens.

**Comment by ChloeDawn** [comment]
It would be nice if you could add wiki documentation or a readme file to the JAR for resource pack developers.

**Comment by ChloeDawn** [comment]
Some further clarification is needed. Looking at the macerator, for example, the `ic2dev` namespace contains a `texture_package.json` and textures for it, but the JSON points to assets in the `ic2` namespace. In the `ic2` namespace, those textures exist, but the `texture_package.json` file in *that* folder points to a plethora of different locations that *aren't* those textures.

`ic2dev:textures/block/machine/lv/macerator` contains `active_dir/inactive_dir` files
`ic2dev:textures/block/machine/lv/macerator/texture_package.json` is:
```json
{
	"active_down": "ic2:block/machine/lv/macerator/active_down",
	"active_east": "ic2:block/machine/lv/macerator/active_east",
	"active_north": "ic2:block/machine/lv/macerator/active_north",
	"active_south": "ic2:block/machine/lv/macerator/active_south",
	"active_up": "ic2:block/machine/lv/macerator/active_up",
	"active_west": "ic2:block/machine/lv/macerator/active_west",
	"inactive_down": "ic2:block/machine/lv/macerator/inactive_down",
	"inactive_east": "ic2:block/machine/lv/macerator/inactive_east",
	"inactive_north": "ic2:block/machine/lv/macerator/inactive_north",
	"inactive_south": "ic2:block/machine/lv/macerator/inactive_south",
	"inactive_up": "ic2:block/machine/lv/macerator/inactive_up",
	"inactive_west": "ic2:block/machine/lv/macerator/inactive_west"
}
```
`ic2:textures/block/machine/lv/macerator` contains `active_dir/inactive_dir` files
`ic2:textures/block/machine/lv/macerator/texture_package.json` is:
```json
{
	"active_down": "ic2:block/electric/battery_station/mv/down",
	"active_east": "ic2:block/electric/energy_storage/mfe/east",
	"active_north": "ic2:block/electric/energy_storage/mfe/east",
	"active_south": "ic2:block/machine/hv/colossal_macerator/active_south",
	"active_up": "ic2:block/machine/lv/macerator/active_up",
	"active_west": "ic2:block/electric/energy_storage/mfe/east",
	"inactive_down": "ic2:block/electric/battery_station/mv/down",
	"inactive_east": "ic2:block/electric/energy_storage/mfe/east",
	"inactive_north": "ic2:block/electric/energy_storage/mfe/east",
	"inactive_south": "ic2:block/machine/hv/colossal_macerator/active_south",
	"inactive_up": "ic2:block/machine/hv/colossal_macerator/inactive_up",
	"inactive_west": "ic2:block/electric/energy_storage/mfe/east"
}
```

This is from the latest 1.19 release on CurseForge

**Comment by Speiger** [comment]
That is due to the program that i ran every time i add new textures. These files are actually automatically generated.
What this program does is:
It goes through every folder and maps the files into said json files. The "active_down" is the key, while the "ic2:block/electric/battery_station/mv/down" is the texture that it is supposed to put with that key (and that is supposed to be loaded)
What this program also does is check if any textures are 100% duplicates. If it is it finds the first texture it scanned and matched and put in this specific texture. If it doesn't find a match then it does insert the current texture being compared.

Why is the "ic2dev" texture different to the "ic2" example. The "dev" textures don't have compression enabled.
To ensure the targets that are found are the correct ones.

Why did i do this?
(note these images are a year old),
We wanted to keep the flexiblity of allowing any side of a texture being set, but have not a insane overhead, so this was my solution.

To give a example:
This is without the new system. 2675 textures being loaded.
![image](https://cdn.discordapp.com/attachments/441859307198349312/1034880313387659264/unknown.png)

This is with the new system and having de-duplication enabled. And down to 1506 textures being loaded.
![image](https://cdn.discordapp.com/attachments/441859307198349312/1034880404949307433/unknown.png)

When i did this i was in a optimization phase where i optimized, SaveFileData, NetworkData, Ram Usage, etc...

If you want I can make a version of the resource pack with all texture_package.json being like the "ic2cdev" version, you showed here. Then you can replace all the textures without any issue.

**Comment by Speiger** [comment]
> It would be nice if you could add wiki documentation or a readme file to the JAR for resource pack developers.

That is planned on the github page...
If you look into the API code, it was half documented when ic2c released.
Basically rushed the "API/Documentation" part because it wasn't as important at the time...

But that will be added soon. I just wanted a week of break.

**Comment by ChloeDawn** [comment]
If `ic2dev` is only used by the program, why do you ship it in the JAR? It would be increasing the size of the JAR a lot, no?

**Comment by Speiger** [comment]
IC2C Dev => IC2Programmer art, and that isn't touched by the program.
only the "ic2" folder is automatically updated.

You mean the .5MB of extra size in the 15MB mod where 15MB textures and 15MB code (uncompressed) are inside?

**Comment by ChloeDawn** [comment]
> If you want I can make a version of the resource pack with all texture_package.json being like the "ic2cdev" version, you showed here. Then you can replace all the textures without any issue.

This would be great, thanks

**Comment by Speiger** [comment]
https://discord.gg/8XwaEuC
PM me, I will send you a version directly. The actual logistic of putting it out will take a few days longer because if i provide one it should also be fully documentated and that will take a few days.

I can at least give you a version early that you guys can try catch.

**Comment by Speiger** [comment]
@ChloeDawn there you go.
https://github.com/TinyModularThings/IC2Classic/wiki/1.19.x-ResourcePacks
(Temp stuff FYI)
